// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrate

import (
	"context"
	"github.com/z9905080/hr_service/environment"
	"github.com/z9905080/hr_service/internal/infra"
)

// Injectors from wire.go:

func Initialize(ctx context.Context) (*App, error) {
	configPathType := environment.StaticPath()
	config := environment.NewConfig(configPathType)
	db, err := infra.NewGormDB(config)
	if err != nil {
		return nil, err
	}
	app := NewApp(db)
	return app, nil
}
